/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HomePage {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PreviewCard {
    }
    interface PreviewSlider {
    }
}
declare global {
    interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {
    }
    var HTMLHomePageElement: {
        prototype: HTMLHomePageElement;
        new (): HTMLHomePageElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPreviewCardElement extends Components.PreviewCard, HTMLStencilElement {
    }
    var HTMLPreviewCardElement: {
        prototype: HTMLPreviewCardElement;
        new (): HTMLPreviewCardElement;
    };
    interface HTMLPreviewSliderElement extends Components.PreviewSlider, HTMLStencilElement {
    }
    var HTMLPreviewSliderElement: {
        prototype: HTMLPreviewSliderElement;
        new (): HTMLPreviewSliderElement;
    };
    interface HTMLElementTagNameMap {
        "home-page": HTMLHomePageElement;
        "my-component": HTMLMyComponentElement;
        "preview-card": HTMLPreviewCardElement;
        "preview-slider": HTMLPreviewSliderElement;
    }
}
declare namespace LocalJSX {
    interface HomePage {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PreviewCard {
    }
    interface PreviewSlider {
    }
    interface IntrinsicElements {
        "home-page": HomePage;
        "my-component": MyComponent;
        "preview-card": PreviewCard;
        "preview-slider": PreviewSlider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "home-page": LocalJSX.HomePage & JSXBase.HTMLAttributes<HTMLHomePageElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "preview-card": LocalJSX.PreviewCard & JSXBase.HTMLAttributes<HTMLPreviewCardElement>;
            "preview-slider": LocalJSX.PreviewSlider & JSXBase.HTMLAttributes<HTMLPreviewSliderElement>;
        }
    }
}
